In [9]:
import pandas as pd
df = pd.read_csv('./public/students.csv')
df
#CRUD Operations

    Name  Age  Height
0  Rahul   10    3.25
1  Priya   12    1.11
2    Tom   14    4.12
3  Jamal   30    5.47
4  Rashi   28    6.15
5    Sai   33    6.67
6  Nidhi   15    2.61

In [8]:
df.T

            0      1     2      3      4     5      6
Name    Rahul  Priya   Tom  Jamal  Rashi   Sai  Nidhi
Age        10     12    14     30     28    33     15
Height   3.25   1.11  4.12   5.47   6.15  6.67   2.61

In [5]:
df.columns

Index(['Name', 'Age', 'Height'], dtype='object')

In [6]:
df.axes

[RangeIndex(start=0, stop=7, step=1),
 Index(['Name', 'Age', 'Height'], dtype='object')]

In [7]:
df.ndim

2

In [8]:
df.dtypes

Name       object
Age         int64
Height    float64
dtype: object

In [9]:
df.shape

(7, 3)

In [10]:
df.head()

    Name  Age  Height
0  Rahul   10    3.25
1  Priya   12    1.11
2    Tom   14    4.12
3  Jamal   30    5.47
4  Rashi   28    6.15

In [11]:
df.head(3)

    Name  Age  Height
0  Rahul   10    3.25
1  Priya   12    1.11
2    Tom   14    4.12

In [16]:
df.tail(2)

    Name  Age  Height
5    Sai   33    6.67
6  Nidhi   15    2.61

In [ ]:
#loc is label based
#iloc is index based

In [26]:
df.loc[0:6,'Name':'Height'] #slicing

    Name  Age  Height
0  Rahul   10    3.25
1  Priya   12    1.11
2    Tom   14    4.12
3  Jamal   30    5.47
4  Rashi   28    6.15
5    Sai   33    6.67
6  Nidhi   15    2.61

In [29]:
df.loc[[2,6],['Name','Height']] #as lists, row|colum, only 2nd and 6th column

    Name  Height
2    Tom    4.12
6  Nidhi    2.61

In [31]:
df.iloc[2:4, 1:2]

   Age
2   14
3   30

In [32]:
df.iloc[[2,6], [0,2]]

    Name  Height
2    Tom    4.12
6  Nidhi    2.61

In [33]:
df[['Name', 'Height']] #filtering some columns

    Name  Height
0  Rahul    3.25
1  Priya    1.11
2    Tom    4.12
3  Jamal    5.47
4  Rashi    6.15
5    Sai    6.67
6  Nidhi    2.61

In [34]:
df[df['Age'] > 20]

    Name  Age  Height
3  Jamal   30    5.47
4  Rashi   28    6.15
5    Sai   33    6.67

In [35]:
df[(df['Age'] > 20) & (df['Height'] < 6)]

    Name  Age  Height
3  Jamal   30    5.47

In [15]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
bunch_data = load_iris()
df = pd.DataFrame(data=bunch_data.data, columns=bunch_data.feature_names)
df['CLASS'] = bunch_data.target
df.columns = ['SL', 'SW', 'PL', 'PW', 'CLASS']
print(df)

      SL   SW   PL   PW  CLASS
0    5.1  3.5  1.4  0.2      0
1    4.9  3.0  1.4  0.2      0
2    4.7  3.2  1.3  0.2      0
3    4.6  3.1  1.5  0.2      0
4    5.0  3.6  1.4  0.2      0
..   ...  ...  ...  ...    ...
145  6.7  3.0  5.2  2.3      2
146  6.3  2.5  5.0  1.9      2
147  6.5  3.0  5.2  2.0      2
148  6.2  3.4  5.4  2.3      2
149  5.9  3.0  5.1  1.8      2

[150 rows x 5 columns]

In [17]:
df = pd.read_csv("./public/iris.data")
le = LabelEncoder()
df["CLASS"] = le.fit_transform(df["CLASS"])
print(df.query("SL > 5 and PL > 2"))

      SL   SW   PL   PW  CLASS
50   7.0  3.2  4.7  1.4      1
51   6.4  3.2  4.5  1.5      1
52   6.9  3.1  4.9  1.5      1
53   5.5  2.3  4.0  1.3      1
54   6.5  2.8  4.6  1.5      1
..   ...  ...  ...  ...    ...
145  6.7  3.0  5.2  2.3      2
146  6.3  2.5  5.0  1.9      2
147  6.5  3.0  5.2  2.0      2
148  6.2  3.4  5.4  2.3      2
149  5.9  3.0  5.1  1.8      2

[96 rows x 5 columns]

In [18]:
df = df.drop(columns = ["PL"], index = [3,4])
print(df)

      SL   SW   PW  CLASS
0    5.1  3.5  0.2      0
1    4.9  3.0  0.2      0
2    4.7  3.2  0.2      0
5    5.4  3.9  0.4      0
6    4.6  3.4  0.3      0
..   ...  ...  ...    ...
145  6.7  3.0  2.3      2
146  6.3  2.5  1.9      2
147  6.5  3.0  2.0      2
148  6.2  3.4  2.3      2
149  5.9  3.0  1.8      2

[148 rows x 4 columns]